server:
  port: 8080
caching:
  ttlmap:
    #key是缓存名称，value是缓存有效期
    users: 10
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://47.102.134.66:61616
    in-memory: false
    pool:
      enabled: true
      max-connections: 50
    packages:
      trust-all: true   #是否信任所有包，信任后所有包内的对象均可序列化传输
  redis:
    database: 0
    host: ENC(v7wYA0vNaELoKwRl4jqzk7PLyTZ8d1H5)
    port: 6379
    password: ENC(BN+9/HIFfSr3D649NP0hCA==)
#    sentinel:     # 哨兵模式连接配置
#      master: mymaster    #master节点名称,redis sentinel模式安装的时候会配置
#      nodes: 47.102.134.66:26379 #,192.168.1.202:26379,192.168.1.203:26379      # 哨兵的IP:Port列表
#    cluster:     #集群模式配置
#      nodes: 47.102.134.66:7000,47.102.134.66:7001,47.102.134.66:7002
#      max-redirects: 3  # 重定向的最大次数
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
  #spring配置缓存层为redis
  cache:
    type: redis
    redis:
      cache-null-values: true   # 缓存null，防止缓存穿透
      use-key-prefix: true  # 是否使用缓存前缀
      key-prefix: boot-launch  # 缓存前缀，缓存按应用分类
      time-to-live:  3600  # 缓存到期时间，默认不主动删除永远不到期
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

datasource:
  primary:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://47.102.134.66:3306/mysql?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: ENC(m0UGzzBFJfGQdK1/oe1tCg==)
    password: ENC(BN+9/HIFfSr3D649NP0hCA==)
    # Hikari will use the above plus the following to setup connection pooling
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:/generator/*.xml
logging:
  level:
    com.example.redis: debug

# 加密所需的salt(盐)
jasypt:
  encryptor:
    password: l&id81!lw            # 根密码用于加密
    algorithm: PBEWithMD5AndDES
  # 加密方式默认为PBEWithMD5AndDES 可以更改为  PBEWithMD5AndTripleDES

#为与项目代码分离的静态资源路径，即：文件上传保存根路径
web:
  upload-path: D:/data/

# MinIo文件服务器
minio:
  endpoint: http://47.102.134.66:9000
  accessKey: PStwBjhgQ1Oee/zHcyP6Qg== # zty314
  secretKey: m22LcoMpFeaMt/oz0M3+Qx984Rw8ASvd # !QAZ2wsx

#默认ActiveMQ只支持点对点模型，想要开启发布订阅模型，需要进行配置
jms:
  pub-sub-domain: true

#rocketmq配置
rocketmq:
  name-server: 47.102.134.66:9876 # 自己的RocketMQ服务地址
  producer:
    send-message-timeout: 300000
    group: launch-group